# Generated by Django 5.2.3 on 2025-06-21 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("heartbeat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heartbeatlog",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
